---

name: lint
on:
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: sudo apt install libgirepository1.0-dev libgtk-3-0
      - run: gradle clean lint
